import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.25rem",
      screens: {
        "2xl": "1320px",
      },
    },
    extend: {
      fontFamily: {
        display: ['"Archivo"', '"Arial Black"', "system-ui", "sans-serif"],
        sans: ['"Instrument Sans"', "system-ui", "-apple-system", '"Segoe UI"', "Roboto", '"PingFang SC"', '"Noto Sans SC"', "sans-serif"],
        mono: ['"IBM Plex Mono"', "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        // Dusk palette: night sky down to the ember line on the horizon.
        night: "#07080c",
        ink: "#0e0f19",
        panel: "#12131f",
        line: "rgba(236, 230, 255, 0.1)",
        paper: "#f3eee6",
        haze: "#a9a4bb",
        dim: "#6f6a84",
        violet: "#9d8cff",
        plum: "#3b2350",
        ember: "#ff6b2c",
        gold: "#ffc15e",
        live: "#ff3b5c",
        mint: "#7fe3b8",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        marquee: { from: { transform: "translate3d(0,0,0)" }, to: { transform: "translate3d(-50%,0,0)" } },
        "slow-zoom": { "0%, 100%": { transform: "scale(1.04) translate3d(0,0,0)" }, "50%": { transform: "scale(1.12) translate3d(-2%,1%,0)" } },
        "live-dot": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.35" } },
        "rise-heart": {
          "0%": { transform: "translate3d(0,0,0) scale(0.6)", opacity: "0" },
          "15%": { opacity: "1" },
          "100%": { transform: "translate3d(var(--drift, -18px),-150px,0) scale(1.1)", opacity: "0" },
        },
        "chat-in": { from: { transform: "translate3d(0,10px,0)", opacity: "0" }, to: { transform: "translate3d(0,0,0)", opacity: "1" } },
        "toast-in": {
          "0%": { transform: "translate3d(-8px,0,0)", opacity: "0" },
          "12%, 80%": { transform: "translate3d(0,0,0)", opacity: "1" },
          "100%": { transform: "translate3d(0,-6px,0)", opacity: "0" },
        },
        "stage-fill": { from: { transform: "scaleX(0)" }, to: { transform: "scaleX(1)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        marquee: "marquee 38s linear infinite",
        "slow-zoom": "slow-zoom 18s ease-in-out infinite",
        "live-dot": "live-dot 1.4s ease-in-out infinite",
        "rise-heart": "rise-heart 2.6s ease-out forwards",
        "chat-in": "chat-in 0.35s ease-out both",
        "toast-in": "toast-in 3.2s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
